#!/bin/sh
#
# AUTHOR: Thanosks
#
# DESC: Elvi to search Gsmarena
# elvis: gsm		-- Search GSMarena (www.gsmarena.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search GSMarena (www.gsmarena.com) for texts 
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.gsmarena.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.gsmarena.com/res.php3?sSearch=${escaped_args}"
fi
